# -*- coding: utf-8 -*-
"""Assignment-3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TkgJ5O4yefVZcPZD0O-1OWQMYQJYf-ms
"""

import numpy as np
import random
from scipy.stats import binom


n=10
p=1/10

Prob_k0=binom.pmf(0,n,p)

sum=0
for i in range(0,10):
  sum=sum+Prob_k0
print(sum)